# golangci-lint configuration for pgtail
# Default configuration per constitution - minimal, practical defaults

run:
  timeout: 5m
  go: "1.21"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 10
