namespace Pgtail.Styling;

/// <summary>
/// The built-in themes.
/// </summary>
public static partial class BuiltInThemes
{
    /// <summary>
    /// The monokai theme: monokai editor color scheme.
    /// </summary>
    public static Theme Monokai { get; } = new(
        "monokai",
        "Monokai editor color scheme",
        new Dictionary<string, ColorStyle>(StringComparer.Ordinal)
        {
            ["PANIC"] = new(Fg: "#f8f8f2", Bg: "#f92672", Bold: true),
            ["FATAL"] = new(Fg: "#f92672", Bold: true),
            ["ERROR"] = new(Fg: "#f92672"),
            ["WARNING"] = new(Fg: "#fd971f"),
            ["NOTICE"] = new(Fg: "#66d9ef"),
            ["LOG"] = new(Fg: "#f8f8f2"),
            ["INFO"] = new(Fg: "#a6e22e"),
            ["DEBUG"] = new(Fg: "#75715e"),
            ["DEBUG1"] = new(Fg: "#75715e"),
            ["DEBUG2"] = new(Fg: "#75715e"),
            ["DEBUG3"] = new(Fg: "#75715e"),
            ["DEBUG4"] = new(Fg: "#75715e"),
            ["DEBUG5"] = new(Fg: "#75715e"),
        },
        new Dictionary<string, ColorStyle>(StringComparer.Ordinal)
        {
            ["prompt"] = new(Fg: "#a6e22e"),
            ["timestamp"] = new(Fg: "#75715e"),
            ["pid"] = new(Fg: "#75715e"),
            ["highlight"] = new(Fg: "#272822", Bg: "#e6db74"),
            ["slow_warning"] = new(Fg: "#fd971f"),
            ["slow_slow"] = new(Fg: "#fd971f", Bold: true),
            ["slow_critical"] = new(Fg: "#f92672", Bold: true),
            ["detail"] = new(Fg: "#f8f8f2"),
            ["sql_keyword"] = new(Fg: "#f92672", Bold: true),
            ["sql_identifier"] = new(Fg: "#66d9ef"),
            ["sql_string"] = new(Fg: "#e6db74"),
            ["sql_number"] = new(Fg: "#ae81ff"),
            ["sql_operator"] = new(Fg: "#f8f8f2"),
            ["sql_comment"] = new(Fg: "#75715e"),
            ["sql_function"] = new(Fg: "#a6e22e"),
            ["status"] = new(Fg: "#f8f8f2", Bg: "#3e3d32"),
            ["status_follow"] = new(Fg: "#a6e22e", Bg: "#3e3d32", Bold: true),
            ["status_paused"] = new(Fg: "#fd971f", Bg: "#3e3d32", Bold: true),
            ["status_error"] = new(Fg: "#f92672", Bg: "#3e3d32", Bold: true),
            ["status_warning"] = new(Fg: "#fd971f", Bg: "#3e3d32"),
            ["status_filter"] = new(Fg: "#66d9ef", Bg: "#3e3d32"),
            ["status_instance"] = new(Fg: "#f8f8f2", Bg: "#3e3d32"),
            ["input"] = new(),
            ["input_prompt"] = new(Fg: "#a6e22e", Bold: true),
            ["separator"] = new(Fg: "#75715e"),
            ["bottom-toolbar"] = new(Fg: "#f8f8f2", Bg: "#3e3d32"),
            ["bottom-toolbar.text"] = new(Fg: "#f8f8f2", Bg: "#3e3d32"),
            ["toolbar"] = new(Fg: "#f8f8f2", Bg: "#3e3d32"),
            ["toolbar.dim"] = new(Fg: "#75715e", Bg: "#3e3d32"),
            ["toolbar.filter"] = new(Fg: "#66d9ef", Bg: "#3e3d32"),
            ["toolbar.warning"] = new(Fg: "#fd971f", Bg: "#3e3d32"),
            ["toolbar.shell"] = new(Fg: "#f8f8f2", Bg: "#3e3d32", Bold: true),
            ["hl_timestamp_date"] = new(Fg: "#75715e"),
            ["hl_timestamp_time"] = new(Fg: "#75715e"),
            ["hl_timestamp_ms"] = new(Fg: "#75715e", Dim: true),
            ["hl_timestamp_tz"] = new(Fg: "#75715e", Dim: true),
            ["hl_pid"] = new(Fg: "#66d9ef"),
            ["hl_context"] = new(Fg: "#fd971f", Bold: true),
            ["hl_sqlstate_success"] = new(Fg: "#a6e22e"),
            ["hl_sqlstate_warning"] = new(Fg: "#fd971f"),
            ["hl_sqlstate_error"] = new(Fg: "#f92672"),
            ["hl_sqlstate_internal"] = new(Fg: "#f92672", Bold: true),
            ["hl_error_name"] = new(Fg: "#f92672"),
            ["hl_duration_fast"] = new(Fg: "#a6e22e"),
            ["hl_duration_slow"] = new(Fg: "#fd971f"),
            ["hl_duration_very_slow"] = new(Fg: "#fd971f", Bold: true),
            ["hl_duration_critical"] = new(Fg: "#f92672", Bold: true),
            ["hl_memory_value"] = new(Fg: "#ae81ff"),
            ["hl_memory_unit"] = new(Fg: "#ae81ff", Dim: true),
            ["hl_statistics"] = new(Fg: "#66d9ef"),
            ["hl_identifier"] = new(Fg: "#66d9ef"),
            ["hl_relation"] = new(Fg: "#66d9ef", Bold: true),
            ["hl_schema"] = new(Fg: "#66d9ef"),
            ["hl_lsn_segment"] = new(Fg: "#ae81ff"),
            ["hl_lsn_offset"] = new(Fg: "#ae81ff", Dim: true),
            ["hl_wal_segment"] = new(Fg: "#ae81ff"),
            ["hl_txid"] = new(Fg: "#ae81ff"),
            ["hl_host"] = new(Fg: "#a6e22e"),
            ["hl_port"] = new(Fg: "#a6e22e", Dim: true),
            ["hl_user"] = new(Fg: "#a6e22e"),
            ["hl_database"] = new(Fg: "#a6e22e", Bold: true),
            ["hl_ip"] = new(Fg: "#a6e22e"),
            ["hl_backend"] = new(Fg: "#66d9ef"),
            ["hl_param"] = new(Fg: "#e6db74"),
            ["hl_lock_share"] = new(Fg: "#e6db74"),
            ["hl_lock_exclusive"] = new(Fg: "#f92672"),
            ["hl_lock_wait"] = new(Fg: "#fd971f", Bold: true),
            ["hl_checkpoint"] = new(Fg: "#ae81ff"),
            ["hl_recovery"] = new(Fg: "#a6e22e"),
            ["hl_bool_true"] = new(Fg: "#a6e22e"),
            ["hl_bool_false"] = new(Fg: "#f92672"),
            ["hl_null"] = new(Fg: "#75715e", Italic: true),
            ["hl_oid"] = new(Fg: "#ae81ff"),
            ["hl_path"] = new(Fg: "#66d9ef"),
        });
}
