namespace Pgtail.Styling;

/// <summary>
/// The built-in themes.
/// </summary>
public static partial class BuiltInThemes
{
    /// <summary>
    /// The dark theme: default dark theme for dark terminal backgrounds.
    /// </summary>
    public static Theme Dark { get; } = new(
        "dark",
        "Default dark theme for dark terminal backgrounds",
        new Dictionary<string, ColorStyle>(StringComparer.Ordinal)
        {
            ["PANIC"] = new(Fg: "white", Bg: "red", Bold: true),
            ["FATAL"] = new(Fg: "red", Bold: true),
            ["ERROR"] = new(Fg: "red"),
            ["WARNING"] = new(Fg: "yellow"),
            ["NOTICE"] = new(Fg: "cyan"),
            ["LOG"] = new(Fg: "ansidefault"),
            ["INFO"] = new(Fg: "green"),
            ["DEBUG"] = new(Fg: "ansibrightblack"),
            ["DEBUG1"] = new(Fg: "ansibrightblack"),
            ["DEBUG2"] = new(Fg: "ansibrightblack"),
            ["DEBUG3"] = new(Fg: "ansibrightblack"),
            ["DEBUG4"] = new(Fg: "ansibrightblack"),
            ["DEBUG5"] = new(Fg: "ansibrightblack"),
        },
        new Dictionary<string, ColorStyle>(StringComparer.Ordinal)
        {
            ["prompt"] = new(Fg: "green"),
            ["timestamp"] = new(Fg: "ansibrightblack"),
            ["pid"] = new(Fg: "ansibrightblack"),
            ["highlight"] = new(Fg: "black", Bg: "yellow"),
            ["slow_warning"] = new(Fg: "yellow"),
            ["slow_slow"] = new(Fg: "yellow", Bold: true),
            ["slow_critical"] = new(Fg: "red", Bold: true),
            ["detail"] = new(Fg: "ansidefault"),
            ["sql_keyword"] = new(Fg: "ansiblue", Bold: true),
            ["sql_identifier"] = new(Fg: "ansicyan"),
            ["sql_string"] = new(Fg: "ansigreen"),
            ["sql_number"] = new(Fg: "ansimagenta"),
            ["sql_operator"] = new(Fg: "ansiyellow"),
            ["sql_comment"] = new(Fg: "ansibrightblack"),
            ["sql_function"] = new(Fg: "ansiblue"),
            ["status"] = new(Fg: "ansiwhite", Bg: "ansiblue"),
            ["status_follow"] = new(Fg: "ansigreen", Bg: "ansiblue", Bold: true),
            ["status_paused"] = new(Fg: "ansiyellow", Bg: "ansiblue", Bold: true),
            ["status_error"] = new(Fg: "ansired", Bg: "ansiblue", Bold: true),
            ["status_warning"] = new(Fg: "ansiyellow", Bg: "ansiblue"),
            ["status_filter"] = new(Fg: "ansicyan", Bg: "ansiblue"),
            ["status_instance"] = new(Fg: "ansiwhite", Bg: "ansiblue"),
            ["input"] = new(),
            ["input_prompt"] = new(Fg: "ansigreen", Bold: true),
            ["separator"] = new(Fg: "ansibrightblack"),
            ["bottom-toolbar"] = new(Fg: "#cccccc", Bg: "#1a1a1a"),
            ["bottom-toolbar.text"] = new(Fg: "#cccccc", Bg: "#1a1a1a"),
            ["toolbar"] = new(Fg: "#cccccc", Bg: "#1a1a1a"),
            ["toolbar.dim"] = new(Fg: "#666666", Bg: "#1a1a1a"),
            ["toolbar.filter"] = new(Fg: "#55ffff", Bg: "#1a1a1a"),
            ["toolbar.warning"] = new(Fg: "#ffff55", Bg: "#1a1a1a"),
            ["toolbar.shell"] = new(Fg: "#ffffff", Bg: "#1a1a1a", Bold: true),
            ["hl_timestamp_date"] = new(Fg: "ansibrightblack"),
            ["hl_timestamp_time"] = new(Fg: "ansibrightblack"),
            ["hl_timestamp_ms"] = new(Fg: "ansibrightblack", Dim: true),
            ["hl_timestamp_tz"] = new(Fg: "ansibrightblack", Dim: true),
            ["hl_pid"] = new(Fg: "ansicyan"),
            ["hl_context"] = new(Fg: "ansiyellow", Bold: true),
            ["hl_sqlstate_success"] = new(Fg: "ansigreen"),
            ["hl_sqlstate_warning"] = new(Fg: "ansiyellow"),
            ["hl_sqlstate_error"] = new(Fg: "ansired"),
            ["hl_sqlstate_internal"] = new(Fg: "ansired", Bold: true),
            ["hl_error_name"] = new(Fg: "ansired"),
            ["hl_duration_fast"] = new(Fg: "ansigreen"),
            ["hl_duration_slow"] = new(Fg: "ansiyellow"),
            ["hl_duration_very_slow"] = new(Fg: "ansibrightyellow", Bold: true),
            ["hl_duration_critical"] = new(Fg: "ansired", Bold: true),
            ["hl_memory_value"] = new(Fg: "ansimagenta"),
            ["hl_memory_unit"] = new(Fg: "ansimagenta", Dim: true),
            ["hl_statistics"] = new(Fg: "ansicyan"),
            ["hl_identifier"] = new(Fg: "ansicyan"),
            ["hl_relation"] = new(Fg: "ansicyan", Bold: true),
            ["hl_schema"] = new(Fg: "ansicyan"),
            ["hl_lsn_segment"] = new(Fg: "ansiblue"),
            ["hl_lsn_offset"] = new(Fg: "ansiblue", Dim: true),
            ["hl_wal_segment"] = new(Fg: "ansiblue"),
            ["hl_txid"] = new(Fg: "ansimagenta"),
            ["hl_host"] = new(Fg: "ansigreen"),
            ["hl_port"] = new(Fg: "ansigreen", Dim: true),
            ["hl_user"] = new(Fg: "ansigreen"),
            ["hl_database"] = new(Fg: "ansigreen", Bold: true),
            ["hl_ip"] = new(Fg: "ansigreen"),
            ["hl_backend"] = new(Fg: "ansicyan"),
            ["hl_param"] = new(Fg: "ansiyellow"),
            ["hl_lock_share"] = new(Fg: "ansiyellow"),
            ["hl_lock_exclusive"] = new(Fg: "ansired"),
            ["hl_lock_wait"] = new(Fg: "ansibrightyellow"),
            ["hl_checkpoint"] = new(Fg: "ansiblue"),
            ["hl_recovery"] = new(Fg: "ansigreen"),
            ["hl_bool_true"] = new(Fg: "ansigreen"),
            ["hl_bool_false"] = new(Fg: "ansired"),
            ["hl_null"] = new(Fg: "ansibrightblack", Italic: true),
            ["hl_oid"] = new(Fg: "ansimagenta"),
            ["hl_path"] = new(Fg: "ansicyan"),
        });
}
