namespace Pgtail.Styling;

/// <summary>
/// The built-in themes.
/// </summary>
public static partial class BuiltInThemes
{
    /// <summary>
    /// The solarized-light theme: solarized light color scheme for reduced eye strain.
    /// </summary>
    public static Theme SolarizedLight { get; } = new(
        "solarized-light",
        "Solarized light color scheme for reduced eye strain",
        new Dictionary<string, ColorStyle>(StringComparer.Ordinal)
        {
            ["PANIC"] = new(Fg: "#fdf6e3", Bg: "#dc322f", Bold: true),
            ["FATAL"] = new(Fg: "#dc322f", Bold: true),
            ["ERROR"] = new(Fg: "#dc322f"),
            ["WARNING"] = new(Fg: "#b58900"),
            ["NOTICE"] = new(Fg: "#2aa198"),
            ["LOG"] = new(Fg: "#657b83"),
            ["INFO"] = new(Fg: "#859900"),
            ["DEBUG"] = new(Fg: "#93a1a1"),
            ["DEBUG1"] = new(Fg: "#93a1a1"),
            ["DEBUG2"] = new(Fg: "#93a1a1"),
            ["DEBUG3"] = new(Fg: "#93a1a1"),
            ["DEBUG4"] = new(Fg: "#93a1a1"),
            ["DEBUG5"] = new(Fg: "#93a1a1"),
        },
        new Dictionary<string, ColorStyle>(StringComparer.Ordinal)
        {
            ["prompt"] = new(Fg: "#859900"),
            ["timestamp"] = new(Fg: "#93a1a1"),
            ["pid"] = new(Fg: "#93a1a1"),
            ["highlight"] = new(Fg: "#fdf6e3", Bg: "#b58900"),
            ["slow_warning"] = new(Fg: "#b58900"),
            ["slow_slow"] = new(Fg: "#cb4b16", Bold: true),
            ["slow_critical"] = new(Fg: "#dc322f", Bold: true),
            ["detail"] = new(Fg: "#657b83"),
            ["sql_keyword"] = new(Fg: "#268bd2", Bold: true),
            ["sql_identifier"] = new(Fg: "#2aa198"),
            ["sql_string"] = new(Fg: "#859900"),
            ["sql_number"] = new(Fg: "#d33682"),
            ["sql_operator"] = new(Fg: "#b58900"),
            ["sql_comment"] = new(Fg: "#93a1a1"),
            ["sql_function"] = new(Fg: "#268bd2"),
            ["status"] = new(Fg: "#657b83", Bg: "#eee8d5"),
            ["status_follow"] = new(Fg: "#859900", Bg: "#eee8d5", Bold: true),
            ["status_paused"] = new(Fg: "#b58900", Bg: "#eee8d5", Bold: true),
            ["status_error"] = new(Fg: "#dc322f", Bg: "#eee8d5", Bold: true),
            ["status_warning"] = new(Fg: "#b58900", Bg: "#eee8d5"),
            ["status_filter"] = new(Fg: "#2aa198", Bg: "#eee8d5"),
            ["status_instance"] = new(Fg: "#657b83", Bg: "#eee8d5"),
            ["input"] = new(),
            ["input_prompt"] = new(Fg: "#859900", Bold: true),
            ["separator"] = new(Fg: "#93a1a1"),
            ["bottom-toolbar"] = new(Fg: "#657b83", Bg: "#eee8d5"),
            ["bottom-toolbar.text"] = new(Fg: "#657b83", Bg: "#eee8d5"),
            ["toolbar"] = new(Fg: "#657b83", Bg: "#eee8d5"),
            ["toolbar.dim"] = new(Fg: "#93a1a1", Bg: "#eee8d5"),
            ["toolbar.filter"] = new(Fg: "#2aa198", Bg: "#eee8d5"),
            ["toolbar.warning"] = new(Fg: "#b58900", Bg: "#eee8d5"),
            ["toolbar.shell"] = new(Fg: "#002b36", Bg: "#eee8d5", Bold: true),
            ["hl_timestamp_date"] = new(Fg: "#93a1a1"),
            ["hl_timestamp_time"] = new(Fg: "#93a1a1"),
            ["hl_timestamp_ms"] = new(Fg: "#93a1a1", Dim: true),
            ["hl_timestamp_tz"] = new(Fg: "#93a1a1", Dim: true),
            ["hl_pid"] = new(Fg: "#2aa198"),
            ["hl_context"] = new(Fg: "#b58900", Bold: true),
            ["hl_sqlstate_success"] = new(Fg: "#859900"),
            ["hl_sqlstate_warning"] = new(Fg: "#b58900"),
            ["hl_sqlstate_error"] = new(Fg: "#dc322f"),
            ["hl_sqlstate_internal"] = new(Fg: "#dc322f", Bold: true),
            ["hl_error_name"] = new(Fg: "#dc322f"),
            ["hl_duration_fast"] = new(Fg: "#859900"),
            ["hl_duration_slow"] = new(Fg: "#b58900"),
            ["hl_duration_very_slow"] = new(Fg: "#cb4b16", Bold: true),
            ["hl_duration_critical"] = new(Fg: "#dc322f", Bold: true),
            ["hl_memory_value"] = new(Fg: "#d33682"),
            ["hl_memory_unit"] = new(Fg: "#d33682", Dim: true),
            ["hl_statistics"] = new(Fg: "#2aa198"),
            ["hl_identifier"] = new(Fg: "#2aa198"),
            ["hl_relation"] = new(Fg: "#2aa198", Bold: true),
            ["hl_schema"] = new(Fg: "#2aa198"),
            ["hl_lsn_segment"] = new(Fg: "#268bd2"),
            ["hl_lsn_offset"] = new(Fg: "#268bd2", Dim: true),
            ["hl_wal_segment"] = new(Fg: "#268bd2"),
            ["hl_txid"] = new(Fg: "#d33682"),
            ["hl_host"] = new(Fg: "#859900"),
            ["hl_port"] = new(Fg: "#859900", Dim: true),
            ["hl_user"] = new(Fg: "#859900"),
            ["hl_database"] = new(Fg: "#859900", Bold: true),
            ["hl_ip"] = new(Fg: "#859900"),
            ["hl_backend"] = new(Fg: "#2aa198"),
            ["hl_param"] = new(Fg: "#b58900"),
            ["hl_lock_share"] = new(Fg: "#b58900"),
            ["hl_lock_exclusive"] = new(Fg: "#dc322f"),
            ["hl_lock_wait"] = new(Fg: "#cb4b16", Bold: true),
            ["hl_checkpoint"] = new(Fg: "#268bd2"),
            ["hl_recovery"] = new(Fg: "#859900"),
            ["hl_bool_true"] = new(Fg: "#859900"),
            ["hl_bool_false"] = new(Fg: "#dc322f"),
            ["hl_null"] = new(Fg: "#93a1a1", Italic: true),
            ["hl_oid"] = new(Fg: "#d33682"),
            ["hl_path"] = new(Fg: "#2aa198"),
        });
}
