namespace Pgtail.Styling;

/// <summary>
/// The built-in themes.
/// </summary>
public static partial class BuiltInThemes
{
    /// <summary>
    /// The light theme: light theme for light terminal backgrounds.
    /// </summary>
    public static Theme Light { get; } = new(
        "light",
        "Light theme for light terminal backgrounds",
        new Dictionary<string, ColorStyle>(StringComparer.Ordinal)
        {
            ["PANIC"] = new(Fg: "white", Bg: "darkred", Bold: true),
            ["FATAL"] = new(Fg: "darkred", Bold: true),
            ["ERROR"] = new(Fg: "darkred"),
            ["WARNING"] = new(Fg: "darkorange"),
            ["NOTICE"] = new(Fg: "darkcyan"),
            ["LOG"] = new(Fg: "ansiblack"),
            ["INFO"] = new(Fg: "darkgreen"),
            ["DEBUG"] = new(Fg: "gray"),
            ["DEBUG1"] = new(Fg: "gray"),
            ["DEBUG2"] = new(Fg: "gray"),
            ["DEBUG3"] = new(Fg: "gray"),
            ["DEBUG4"] = new(Fg: "gray"),
            ["DEBUG5"] = new(Fg: "gray"),
        },
        new Dictionary<string, ColorStyle>(StringComparer.Ordinal)
        {
            ["prompt"] = new(Fg: "darkgreen"),
            ["timestamp"] = new(Fg: "gray"),
            ["pid"] = new(Fg: "gray"),
            ["highlight"] = new(Fg: "black", Bg: "yellow"),
            ["slow_warning"] = new(Fg: "darkorange"),
            ["slow_slow"] = new(Fg: "darkorange", Bold: true),
            ["slow_critical"] = new(Fg: "darkred", Bold: true),
            ["detail"] = new(Fg: "ansiblack"),
            ["sql_keyword"] = new(Fg: "darkblue", Bold: true),
            ["sql_identifier"] = new(Fg: "teal"),
            ["sql_string"] = new(Fg: "darkgreen"),
            ["sql_number"] = new(Fg: "darkmagenta"),
            ["sql_operator"] = new(Fg: "darkorange"),
            ["sql_comment"] = new(Fg: "gray"),
            ["sql_function"] = new(Fg: "darkblue"),
            ["status"] = new(Fg: "ansiblack", Bg: "silver"),
            ["status_follow"] = new(Fg: "darkgreen", Bg: "silver", Bold: true),
            ["status_paused"] = new(Fg: "darkorange", Bg: "silver", Bold: true),
            ["status_error"] = new(Fg: "darkred", Bg: "silver", Bold: true),
            ["status_warning"] = new(Fg: "darkorange", Bg: "silver"),
            ["status_filter"] = new(Fg: "teal", Bg: "silver"),
            ["status_instance"] = new(Fg: "ansiblack", Bg: "silver"),
            ["input"] = new(),
            ["input_prompt"] = new(Fg: "darkgreen", Bold: true),
            ["separator"] = new(Fg: "gray"),
            ["bottom-toolbar"] = new(Fg: "#333333", Bg: "#e0e0e0"),
            ["bottom-toolbar.text"] = new(Fg: "#333333", Bg: "#e0e0e0"),
            ["toolbar"] = new(Fg: "#333333", Bg: "#e0e0e0"),
            ["toolbar.dim"] = new(Fg: "#888888", Bg: "#e0e0e0"),
            ["toolbar.filter"] = new(Fg: "#007acc", Bg: "#e0e0e0"),
            ["toolbar.warning"] = new(Fg: "#d9831f", Bg: "#e0e0e0"),
            ["toolbar.shell"] = new(Fg: "#000000", Bg: "#e0e0e0", Bold: true),
            ["hl_timestamp_date"] = new(Fg: "gray"),
            ["hl_timestamp_time"] = new(Fg: "gray"),
            ["hl_timestamp_ms"] = new(Fg: "gray", Dim: true),
            ["hl_timestamp_tz"] = new(Fg: "gray", Dim: true),
            ["hl_pid"] = new(Fg: "teal"),
            ["hl_context"] = new(Fg: "darkorange", Bold: true),
            ["hl_sqlstate_success"] = new(Fg: "darkgreen"),
            ["hl_sqlstate_warning"] = new(Fg: "darkorange"),
            ["hl_sqlstate_error"] = new(Fg: "darkred"),
            ["hl_sqlstate_internal"] = new(Fg: "darkred", Bold: true),
            ["hl_error_name"] = new(Fg: "darkred"),
            ["hl_duration_fast"] = new(Fg: "darkgreen"),
            ["hl_duration_slow"] = new(Fg: "darkorange"),
            ["hl_duration_very_slow"] = new(Fg: "darkorange", Bold: true),
            ["hl_duration_critical"] = new(Fg: "darkred", Bold: true),
            ["hl_memory_value"] = new(Fg: "darkmagenta"),
            ["hl_memory_unit"] = new(Fg: "darkmagenta", Dim: true),
            ["hl_statistics"] = new(Fg: "teal"),
            ["hl_identifier"] = new(Fg: "teal"),
            ["hl_relation"] = new(Fg: "teal", Bold: true),
            ["hl_schema"] = new(Fg: "teal"),
            ["hl_lsn_segment"] = new(Fg: "darkblue"),
            ["hl_lsn_offset"] = new(Fg: "darkblue", Dim: true),
            ["hl_wal_segment"] = new(Fg: "darkblue"),
            ["hl_txid"] = new(Fg: "darkmagenta"),
            ["hl_host"] = new(Fg: "darkgreen"),
            ["hl_port"] = new(Fg: "darkgreen", Dim: true),
            ["hl_user"] = new(Fg: "darkgreen"),
            ["hl_database"] = new(Fg: "darkgreen", Bold: true),
            ["hl_ip"] = new(Fg: "darkgreen"),
            ["hl_backend"] = new(Fg: "teal"),
            ["hl_param"] = new(Fg: "darkorange"),
            ["hl_lock_share"] = new(Fg: "darkorange"),
            ["hl_lock_exclusive"] = new(Fg: "darkred"),
            ["hl_lock_wait"] = new(Fg: "darkorange", Bold: true),
            ["hl_checkpoint"] = new(Fg: "darkblue"),
            ["hl_recovery"] = new(Fg: "darkgreen"),
            ["hl_bool_true"] = new(Fg: "darkgreen"),
            ["hl_bool_false"] = new(Fg: "darkred"),
            ["hl_null"] = new(Fg: "gray", Italic: true),
            ["hl_oid"] = new(Fg: "darkmagenta"),
            ["hl_path"] = new(Fg: "teal"),
        });
}
