namespace Pgtail.Styling;

/// <summary>
/// The built-in themes.
/// </summary>
public static partial class BuiltInThemes
{
    /// <summary>
    /// The high-contrast theme: high contrast theme for accessibility.
    /// </summary>
    public static Theme HighContrast { get; } = new(
        "high-contrast",
        "High contrast theme for accessibility",
        new Dictionary<string, ColorStyle>(StringComparer.Ordinal)
        {
            ["PANIC"] = new(Fg: "white", Bg: "red", Bold: true),
            ["FATAL"] = new(Fg: "red", Bold: true),
            ["ERROR"] = new(Fg: "red", Bold: true),
            ["WARNING"] = new(Fg: "yellow", Bold: true),
            ["NOTICE"] = new(Fg: "cyan", Bold: true),
            ["LOG"] = new(Fg: "white"),
            ["INFO"] = new(Fg: "green", Bold: true),
            ["DEBUG"] = new(Fg: "white", Dim: true),
            ["DEBUG1"] = new(Fg: "white", Dim: true),
            ["DEBUG2"] = new(Fg: "white", Dim: true),
            ["DEBUG3"] = new(Fg: "white", Dim: true),
            ["DEBUG4"] = new(Fg: "white", Dim: true),
            ["DEBUG5"] = new(Fg: "white", Dim: true),
        },
        new Dictionary<string, ColorStyle>(StringComparer.Ordinal)
        {
            ["prompt"] = new(Fg: "green", Bold: true),
            ["timestamp"] = new(Fg: "white"),
            ["pid"] = new(Fg: "white"),
            ["highlight"] = new(Fg: "black", Bg: "yellow", Bold: true),
            ["slow_warning"] = new(Fg: "yellow", Bold: true),
            ["slow_slow"] = new(Fg: "yellow", Bold: true, Underline: true),
            ["slow_critical"] = new(Fg: "red", Bold: true, Underline: true),
            ["detail"] = new(Fg: "white"),
            ["sql_keyword"] = new(Fg: "blue", Bold: true),
            ["sql_identifier"] = new(Fg: "cyan", Bold: true),
            ["sql_string"] = new(Fg: "green", Bold: true),
            ["sql_number"] = new(Fg: "magenta", Bold: true),
            ["sql_operator"] = new(Fg: "yellow", Bold: true),
            ["sql_comment"] = new(Fg: "white", Dim: true),
            ["sql_function"] = new(Fg: "blue", Bold: true),
            ["status"] = new(Fg: "white", Bg: "ansiblack", Bold: true),
            ["status_follow"] = new(Fg: "green", Bg: "ansiblack", Bold: true),
            ["status_paused"] = new(Fg: "yellow", Bg: "ansiblack", Bold: true),
            ["status_error"] = new(Fg: "red", Bg: "ansiblack", Bold: true, Underline: true),
            ["status_warning"] = new(Fg: "yellow", Bg: "ansiblack", Bold: true),
            ["status_filter"] = new(Fg: "cyan", Bg: "ansiblack", Bold: true),
            ["status_instance"] = new(Fg: "white", Bg: "ansiblack", Bold: true),
            ["input"] = new(),
            ["input_prompt"] = new(Fg: "green", Bold: true),
            ["separator"] = new(Fg: "white"),
            ["bottom-toolbar"] = new(Fg: "white", Bg: "ansiblack"),
            ["bottom-toolbar.text"] = new(Fg: "white", Bg: "ansiblack"),
            ["toolbar"] = new(Fg: "white", Bg: "ansiblack", Bold: true),
            ["toolbar.dim"] = new(Fg: "white", Bg: "ansiblack"),
            ["toolbar.filter"] = new(Fg: "cyan", Bg: "ansiblack", Bold: true),
            ["toolbar.warning"] = new(Fg: "yellow", Bg: "ansiblack", Bold: true),
            ["toolbar.shell"] = new(Fg: "white", Bg: "ansiblack", Bold: true, Underline: true),
            ["hl_timestamp_date"] = new(Fg: "white"),
            ["hl_timestamp_time"] = new(Fg: "white"),
            ["hl_timestamp_ms"] = new(Fg: "white", Dim: true),
            ["hl_timestamp_tz"] = new(Fg: "white", Dim: true),
            ["hl_pid"] = new(Fg: "cyan", Bold: true),
            ["hl_context"] = new(Fg: "yellow", Bold: true),
            ["hl_sqlstate_success"] = new(Fg: "green", Bold: true),
            ["hl_sqlstate_warning"] = new(Fg: "yellow", Bold: true),
            ["hl_sqlstate_error"] = new(Fg: "red", Bold: true),
            ["hl_sqlstate_internal"] = new(Fg: "red", Bold: true, Underline: true),
            ["hl_error_name"] = new(Fg: "red", Bold: true),
            ["hl_duration_fast"] = new(Fg: "green", Bold: true),
            ["hl_duration_slow"] = new(Fg: "yellow", Bold: true),
            ["hl_duration_very_slow"] = new(Fg: "yellow", Bold: true, Underline: true),
            ["hl_duration_critical"] = new(Fg: "red", Bold: true, Underline: true),
            ["hl_memory_value"] = new(Fg: "magenta", Bold: true),
            ["hl_memory_unit"] = new(Fg: "magenta", Bold: true),
            ["hl_statistics"] = new(Fg: "cyan", Bold: true),
            ["hl_identifier"] = new(Fg: "cyan", Bold: true),
            ["hl_relation"] = new(Fg: "cyan", Bold: true, Underline: true),
            ["hl_schema"] = new(Fg: "cyan", Bold: true),
            ["hl_lsn_segment"] = new(Fg: "blue", Bold: true),
            ["hl_lsn_offset"] = new(Fg: "blue", Bold: true),
            ["hl_wal_segment"] = new(Fg: "blue", Bold: true),
            ["hl_txid"] = new(Fg: "magenta", Bold: true),
            ["hl_host"] = new(Fg: "green", Bold: true),
            ["hl_port"] = new(Fg: "green", Bold: true),
            ["hl_user"] = new(Fg: "green", Bold: true),
            ["hl_database"] = new(Fg: "green", Bold: true, Underline: true),
            ["hl_ip"] = new(Fg: "green", Bold: true),
            ["hl_backend"] = new(Fg: "cyan", Bold: true),
            ["hl_param"] = new(Fg: "yellow", Bold: true),
            ["hl_lock_share"] = new(Fg: "yellow", Bold: true),
            ["hl_lock_exclusive"] = new(Fg: "red", Bold: true),
            ["hl_lock_wait"] = new(Fg: "yellow", Bold: true, Underline: true),
            ["hl_checkpoint"] = new(Fg: "blue", Bold: true),
            ["hl_recovery"] = new(Fg: "green", Bold: true),
            ["hl_bool_true"] = new(Fg: "green", Bold: true),
            ["hl_bool_false"] = new(Fg: "red", Bold: true),
            ["hl_null"] = new(Fg: "white", Italic: true),
            ["hl_oid"] = new(Fg: "magenta", Bold: true),
            ["hl_path"] = new(Fg: "cyan", Bold: true),
        });
}
