# Contract: GitHub Actions Release Workflow Structure
# This defines the expected structure and behavior of the release workflow

name: Release Workflow Contract

# Trigger: Push of version tags
trigger:
  on:
    push:
      tags:
        - 'v*'

# Permissions required
permissions:
  contents: write    # Create releases
  issues: write      # Create failure issues

# Job structure
jobs:
  # Phase 1: Build binaries for all platforms
  build-unix:
    runs-on: matrix.os
    matrix:
      include:
        - os: macos-14
          platform: macos
          arch: arm64
        - os: macos-15-intel
          platform: macos
          arch: x86_64
        - os: ubuntu-latest
          platform: linux
          arch: x86_64
        - os: ubuntu-24.04-arm
          platform: linux
          arch: arm64

    steps:
      - checkout
      - setup-python: '3.12'
      - setup-uv
      - uv-sync: --extra dev
      - nuitka-build:
          mode: standalone
          output-dir: dist
          output-filename: pgtail
          include-package:
            - pgtail_py
            - psutil
          include-package-data: certifi
          include-module:
            - pgtail_py.detector_unix
            - pgtail_py.detector_windows
            - pgtail_py.notifier_unix
            - pgtail_py.notifier_windows
          flags:
            - --python-flag=no_asserts
            - --assume-yes-for-downloads
      - rename-output: pgtail.dist -> pgtail-{platform}-{arch}
      - verify-build: ./dist/pgtail-{platform}-{arch}/pgtail --version
      - create-archive: tar.gz
      - upload-artifact: pgtail-{platform}-{arch}.tar.gz

  build-windows:
    runs-on: windows-latest

    steps:
      - checkout
      - setup-python: '3.12'
      - setup-uv
      - uv-sync: --extra dev
      - nuitka-build: (same as Unix)
      - rename-output: pgtail.dist -> pgtail-windows-x86_64
      - verify-build: .\dist\pgtail-windows-x86_64\pgtail.exe --version
      - create-zip: pgtail-windows-x86_64.zip
      - build-msi:
          wix-version: 5.0.0
          upgrade-code: F8E7D6C5-B4A3-9281-7654-321098FEDCBA
          output: pgtail-windows-x86_64.msi
      - upload-artifacts:
          - pgtail-windows-x86_64.zip
          - pgtail-windows-x86_64.msi

  # Phase 2: Create GitHub Release
  release:
    needs: [build-unix, build-windows]
    runs-on: ubuntu-latest

    steps:
      - download-all-artifacts
      - prepare-release-files
      - calculate-sha256-checksums
      - create-github-release:
          files:
            - pgtail-macos-arm64.tar.gz
            - pgtail-macos-arm64.tar.gz.sha256
            - pgtail-macos-x86_64.tar.gz
            - pgtail-macos-x86_64.tar.gz.sha256
            - pgtail-linux-x86_64.tar.gz
            - pgtail-linux-x86_64.tar.gz.sha256
            - pgtail-linux-arm64.tar.gz
            - pgtail-linux-arm64.tar.gz.sha256
            - pgtail-windows-x86_64.zip
            - pgtail-windows-x86_64.zip.sha256
            - pgtail-windows-x86_64.msi
            - pgtail-windows-x86_64.msi.sha256

  # Phase 3: Update package managers
  update-homebrew:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - extract-version-from-tag
      - clone-homebrew-tap
      - download-checksums
      - update-formula:
          version: {version}
          sha256:
            macos-arm64: {checksum}
            macos-x86_64: {checksum}
            linux-arm64: {checksum}
            linux-x86_64: {checksum}
      - commit-and-push

  update-winget:
    needs: release
    runs-on: windows-latest
    # NOTE: Uses wingetcreate which pushes to fork (willibrandon/winget-pkgs)
    # and opens PR to microsoft/winget-pkgs. Cannot push directly to upstream.

    steps:
      - extract-version-from-tag
      - download-msi-and-extract-productcode  # ProductCode changes per build
      - check-package-exists
      - install-wingetcreate
      - create-or-update-manifest:
          package-identifier: willibrandon.pgtail
          version: {version}
          installer-url: https://github.com/willibrandon/pgtail/releases/download/v{version}/pgtail-windows-x86_64.msi
          installer-sha256: {checksum}
          product-code: {extracted-from-msi}  # Auto-generated by WiX, must be extracted
      - submit-pr-via-fork:  # wingetcreate --submit handles fork workflow
          fork: willibrandon/winget-pkgs
          upstream: microsoft/winget-pkgs

  # Phase 4: Failure notification
  notify-failure:
    needs: [build-unix, build-windows, release, update-homebrew, update-winget]
    if: failure()
    runs-on: ubuntu-latest

    steps:
      - create-github-issue:
          title: "Release {tag} failed"
          labels: [bug, release]

# Expected outputs
outputs:
  release-artifacts:
    - pgtail-macos-arm64.tar.gz
    - pgtail-macos-x86_64.tar.gz
    - pgtail-linux-x86_64.tar.gz
    - pgtail-linux-arm64.tar.gz
    - pgtail-windows-x86_64.zip
    - pgtail-windows-x86_64.msi
    - (all with .sha256 checksums)

  homebrew-update:
    repository: willibrandon/homebrew-tap
    file: Formula/pgtail.rb
    changes: version, sha256 values

  winget-update:
    fork: willibrandon/winget-pkgs  # Push to fork, PR to upstream
    upstream: microsoft/winget-pkgs
    directory: manifests/w/willibrandon/pgtail/{version}/
    files:
      - willibrandon.pgtail.yaml
      - willibrandon.pgtail.installer.yaml
      - willibrandon.pgtail.locale.en-US.yaml
    notes:
      - ProductCode extracted from built MSI (changes per version)
      - wingetcreate --submit handles fork-to-upstream PR workflow

# Time constraints
timing:
  build-per-platform: 15-20 minutes
  total-workflow: < 30 minutes (parallel builds)
  timeout-per-job: 30 minutes
