<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>pgtail</AssemblyName>
    <RootNamespace>Pgtail</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
    <PublishAot>true</PublishAot>
    <RuntimeIdentifiers>win-x64;win-arm64;linux-x64;linux-arm64;osx-x64;osx-arm64</RuntimeIdentifiers>
    <OptimizationPreference>Speed</OptimizationPreference>
    <StripSymbols>true</StripSymbols>
    <StackTraceSupport>true</StackTraceSupport>
    <ApplicationIcon>../../art/pgtail.ico</ApplicationIcon>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hex1b" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Pgtail.Core/Pgtail.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Pgtail.Tests" />
  </ItemGroup>

</Project>
